### ISSUE TITLE
2/10/20 REVIEW

### ISSUE THREAD

**Issue by aliao3511** [phongngo91/unLeashd#2]
Hey Phong!

Good work on your design docs! I have a couple of notes:

**MVPs**

- dog CRUD should come before the user profile
- checkins CRUD/feed can probably be worked on at the same time
- I'd recommend adding some search functionality before fleshing out user profiles

**Schema**

- assuming that the dog breeds resource is just to represent instances of dogs, add  name and description column
- add password_digest to schema

**Comment by phongngo91** [comment]
Changed pushed.
